### ISSUE TITLE
Minor typo in API Docs Quickstart

### ISSUE THREAD

**Issue by joeldfsutton** [loonanalytics/LoonAnalytics.jl#1]
Item 2 reads 'yer' instead of 'your'. Unbelievable.

**Comment by joeldfsutton** [comment]
Can't assign it to myself for some reason (still figuring out the GitHub issues UI). I'm going to submit a fix though.

**Comment by joeldfsutton** [comment]
I apparently don't have permissions to create a branch in the repo. Tried to push my local branch and got "permission denied to joeldfsutton"

**Comment by joshday** [comment]
You should have permissions now.  Also, fixed.
